/**
 * Phase 6: Post-installation tasks
 * Enhanced UX: Auto-install deps, verify credentials, fetch project info
 */

import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join } from "node:path";
import * as p from "@clack/prompts";
import type { InitContext } from "../types.js";
import { logger } from "../../../shared/logger.js";

/**
 * Verify Backlog credentials by making API call
 */
async function verifyBacklogCredentials(
  spaceUrl: string,
  apiKey: string
): Promise<{ success: boolean; spaceName?: string; error?: string }> {
  try {
    const url = `${spaceUrl}/api/v2/space?apiKey=${apiKey}`;
    const response = await fetch(url, {
      headers: { "User-Agent": "BrseKit-CLI/1.0" },
    });

    if (!response.ok) {
      if (response.status === 401) {
        return { success: false, error: "Invalid API key" };
      }
      return { success: false, error: `HTTP ${response.status}` };
    }

    const data = await response.json();
    return { success: true, spaceName: data.name };
  } catch (error) {
    return { success: false, error: String(error) };
  }
}

/**
 * Run install script if exists
 * @param skillsDir - Path to skills directory
 * @param autoConfirm - If true, pass -Y/-y flag to skip prompts
 */
async function runInstallScript(
  skillsDir: string,
  autoConfirm: boolean = false
): Promise<boolean> {
  const isWindows = process.platform === "win32";
  const scriptName = isWindows ? "install.ps1" : "install.sh";
  const scriptPath = join(skillsDir, scriptName);

  if (!existsSync(scriptPath)) {
    logger.verbose("No install script found");
    return true;
  }

  logger.verbose(`Running ${scriptName}${autoConfirm ? " (auto-confirm)" : ""}`);

  try {
    if (isWindows) {
      // -Y flag skips all prompts in install.ps1
      const yesFlag = autoConfirm ? " -Y" : "";
      execSync(
        `powershell -ExecutionPolicy Bypass -File "${scriptPath}"${yesFlag}`,
        {
          cwd: skillsDir,
          stdio: "inherit",
        }
      );
    } else {
      // -y flag skips all prompts in install.sh
      const yesFlag = autoConfirm ? " -y" : "";
      execSync(`bash "${scriptPath}"${yesFlag}`, {
        cwd: skillsDir,
        stdio: "inherit",
      });
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if .env exists, prompt to create if not
 */
async function checkEnvFile(
  skillsDir: string,
  isNonInteractive: boolean
): Promise<void> {
  const envPath = join(skillsDir, ".env");
  const envExamplePath = join(skillsDir, ".env.example");

  if (existsSync(envPath)) {
    logger.verbose(".env file exists");
    return;
  }

  if (!existsSync(envExamplePath)) {
    logger.verbose("No .env.example found");
    return;
  }

  p.log.warning("No .env file found.");

  if (isNonInteractive) {
    p.log.info("Copy .env.example to .env and configure your credentials.");
    return;
  }

  const shouldCreate = await p.confirm({
    message: "Would you like to configure credentials now?",
  });

  if (p.isCancel(shouldCreate) || !shouldCreate) {
    p.log.info("You can configure later by copying .env.example to .env");
    return;
  }

  // Prompt for credentials
  const credentials = await p.group({
    backlogUrl: () =>
      p.text({
        message: "Backlog Space URL",
        placeholder: "https://xxx.backlog.jp",
        validate: (value) => {
          if (!value) return "Required";
          if (!value.includes("backlog")) return "Invalid Backlog URL";
        },
      }),
    apiKey: () =>
      p.password({
        message: "Backlog API Key",
        validate: (value) => {
          if (!value) return "Required";
        },
      }),
    projectKey: () =>
      p.text({
        message: "Backlog Project Key",
        placeholder: "PROJECT",
        validate: (value) => {
          if (!value) return "Required";
        },
      }),
  });

  if (p.isCancel(credentials)) {
    return;
  }

  // Verify credentials before saving
  const verifySpinner = p.spinner();
  verifySpinner.start("Verifying Backlog credentials...");

  const verification = await verifyBacklogCredentials(
    credentials.backlogUrl as string,
    credentials.apiKey as string
  );

  if (verification.success) {
    verifySpinner.stop(`✓ Connected to: ${verification.spaceName}`);
  } else {
    verifySpinner.stop(`⚠ Verification failed: ${verification.error}`);
    const continueAnyway = await p.confirm({
      message: "Continue with these credentials anyway?",
      initialValue: false,
    });
    if (p.isCancel(continueAnyway) || !continueAnyway) {
      p.log.info("Please check your credentials and try again.");
      return;
    }
  }

  // Write .env file
  const envContent = `# BrseKit Configuration
# Generated by bk init
BACKLOG_SPACE_URL=${credentials.backlogUrl}
BACKLOG_API_KEY=${credentials.apiKey}
BACKLOG_PROJECT_KEY=${credentials.projectKey}

# Optional: Google API for semantic search
# GOOGLE_API_KEY=your-gemini-api-key
`;

  const fs = await import("node:fs/promises");
  await fs.writeFile(envPath, envContent);
  p.log.success("Created .env file");

  // Show next steps
  if (verification.success) {
    p.note(
      `Space: ${verification.spaceName}\nProject: ${credentials.projectKey}\n\nRun in Claude Code:\n  /bk-track status    Check project health\n  /bk-init            Complete setup wizard`,
      "Ready to use!"
    );
  }
}

/**
 * Handle post-installation tasks
 * UX principle: Auto-install deps silently, only ask for credentials
 */
export async function handlePostInstall(ctx: InitContext): Promise<InitContext> {
  logger.verbose("Running post-installation tasks");

  // Step 1: Auto-install dependencies (user shouldn't run commands manually)
  if (ctx.skipDeps) {
    logger.verbose("Skipping dependency installation (--skip-deps)");
  } else {
    const spinner = p.spinner();
    spinner.start("Setting up environment...");

    const success = await runInstallScript(ctx.skillsDir, true);

    if (success) {
      spinner.stop("✓ Environment ready");
    } else {
      spinner.stop("⚠ Environment setup incomplete");
      logger.verbose("Install script failed, but continuing...");
    }
  }

  // Step 2: Check/create .env with credential verification
  await checkEnvFile(ctx.skillsDir, ctx.isNonInteractive);

  // Step 3: Show what to do next
  if (!ctx.isNonInteractive) {
    console.log(); // spacing
    p.log.info("🚀 BrseKit installed! Open Claude Code and run:");
    console.log();
    console.log("  /bk-init           Complete interactive setup");
    console.log("  /bk-track status   Check project health");
    console.log("  /brsekit help      See all available skills");
    console.log();
  }

  return ctx;
}
